### PR TITLE
Fix problem with DAC name on Linux.

### PR DESCRIPTION
**Pull request by mikem8361**
The current code forgot to prepend "lib" to the name of the DAC module.

### CODE REVIEW

**Comment by leculver** [comment]
LGTM, thank you!

**Comment by mikem8361** [comment]
When and what will the package version be with this change?

**Comment by leculver** [comment]
Packages are created manually.  If you need one with this change I can go have one built.

**Comment by mikem8361** [comment]
Yes, I need one.  Most .NET Core repos publish the package in their official build automatically.

Thanks.

**Comment by leculver** [comment]
I will put this together tomorrow.

ClrMD isn't one of the ones that get daily builds. =(

**Comment by mikem8361** [comment]
You probably should wait to do this build/publish.  Now I’m running into the “LTTng-UST: Error (-17) while registering tracepoint probe. Duplicate registration of tracepoint probes having the same name is not allowed” crash because of the DAC and the hosting coreclr load/registering the tracepoints twice.  I worked around this in SOS by creating a symbol link of the DAC into a temp dir/file and loading that.  I know you ran into this a while back when you first were porting clrmd and I thought you worked around it.

In order for clrmd on Linux to work, it will need to do something similar.  I look into this and get back to you.

**Pull request merged**
