### PR TITLE
Use WINAPI calling convention for DAC APIs

### PR DESCRIPTION
**Pull request by NextTurn**
See https://github.com/dotnet/diagnostics/issues/846#issuecomment-604231358

Thanks @swift-kim

### CODE REVIEW

**Comment by swift-kim** [comment]
Thanks! @leculver Do you mind if we do the same for 1.1?

**Comment by swift-kim** [comment]
Do you think https://github.com/microsoft/clrmd/compare/master...NextTurn:x86 or https://github.com/microsoft/clrmd/compare/release/1.1...NextTurn:v1-x86 needs any rework?

**Comment by NextTurn** [comment]
> Do you think [master...NextTurn:x86](https://github.com/microsoft/clrmd/compare/master...NextTurn:x86) or [release/1.1...NextTurn:v1-x86](https://github.com/microsoft/clrmd/compare/release/1.1...NextTurn:v1-x86) needs any rework?

Not really. I didn't implement support for debug registers and floating point registers but I don't think they matter.

**Comment by NextTurn** [comment]
We can update the DbgEng APIs to use WINAPI as well (for consistency).

**Pull request merged**
