### PR TITLE
Improve ElfVirtualAddressSpace.Read

### PR DESCRIPTION
**Pull request by NextTurn**

### CODE REVIEW

**Comment by leculver** [comment]
LGTM if this is ready for review/merge.

**Comment by NextTurn** [comment]
This isn't ready. I'll see if this really helps.

Other PRs will be ready for review as soon as I resolve the conflicts.

**Comment by leculver** [comment]
I think I'll probably need to make bigger changes to the linux coredump reader before 2.0 is released.  In the short term I need to make the class thread-safe.  I'd like to close this PR (or merge it) within the next couple days so it's not an outstanding pull request when that work goes in.

Bigger picture though I am not super happy with the design of how we read data out of the target process using nested "address spaces" that boil down to reading a Stream.  It makes debugging problems with the code a real pain stepping through layers of indirection.

If I have time early next week I _think_ I'm going to rewrite it all using MemoryMappedFile.  Let me know how you want to proceed with this PR.  I think the cleanups you have here are good, but I worry I'm just going to delete them if I get around to rewriting the coredump reader next week.

Lastly, I wanted to give you a heads up on some upcoming work I'm doing.  I'm trying to wrap up most of the major ClrMD changes by mid next week and publish a build.  I'll be out of office on vacation from Dec20-Jan6 or so, buy I may work on the project some in my spare time.

I've also deleted the testing/2.0 branch.  We are stable enough (well, stable-ish) that I don't think we need a separate branch.  I plan to just use the master branch for 2.0 until I'm ready to branch it after 2.0 is released.

**Comment by leculver** [comment]
Whoops, I think deleting the branch closed this PR, or maybe I accidently hit the Close and comment button.  Sorry about that.

Happy to accept these changes if they are wrapped up before I start working on this client (and if submitted against master since this branch is dead).

**Comment by NextTurn** [comment]
Yeah quite stable. :)

This is put aside because a bunch of tests failed every time I wanted to collect some coverage data on Linux. I was willing to help but none of my Linux VMs worked fine in recent days. I've just installed WSL 2 today but the tests are running super slowly.

Since you are going to rewrite the coredump reader these updates to the old implementation are unneeded.

Here are the current test results on Linux,

```
Total tests: 107
     Passed: 34
     Failed: 52
    Skipped: 21
 Total time: 46.7432 Seconds
```

and on my WSL 2,

```
Total tests: 107
     Passed: 35
     Failed: 51
    Skipped: 21
 Total time: 3.6912 Minutes
```

**Comment by leculver** [comment]
haha well "stable" was the wrong word...I mean at least it compiles and produces some results.  I haven't even started Linux testing yet.  =)

I am going to wrap up a few other bits of work today and hopefully get to work on fixing Linux problems Thursday or Friday.  Does WSL 2 still require Windows Insider builds?

**Comment by NextTurn** [comment]
> Does WSL 2 still require Windows Insider builds?

Yes.

**Pull request closed without merging**
