### PR TITLE
Enable tests on Linux

### PR DESCRIPTION
**Pull request by NextTurn**
`HeapTests.ServerSegmentTests` is failing.
`RuntimeTests.CreationSpecificDacNegativeTest` is skipped.

### CODE REVIEW

**Comment by leculver** [comment]
Much appreciated!

**Comment by leculver** [comment]
Odd, won't build for me:

    leculver@leculver-ubuntu:~/clrmd/src/TestTargets$ dotnet build TestTargets.proj
    Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.

    /home/leculver/clrmd/src/TestTargets/TestTargets.proj(64,5): error MSB6003: The specified task executable "sh" could not be run. System.ComponentModel.Win32Exception (2): No such file or directory
    /home/leculver/clrmd/src/TestTargets/TestTargets.proj(64,5): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
    /home/leculver/clrmd/src/TestTargets/TestTargets.proj(64,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
    /home/leculver/clrmd/src/TestTargets/TestTargets.proj(64,5): error MSB6003:    at System.Diagnostics.Process.Start()
    /home/leculver/clrmd/src/TestTargets/TestTargets.proj(64,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
    /home/leculver/clrmd/src/TestTargets/TestTargets.proj(64,5): error MSB6003:    at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
    /home/leculver/clrmd/src/TestTargets/TestTargets.proj(64,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()

    Build FAILED.

Seen this before?  If not I'll dig into it later today  Looks like a machine configuration issue of some sort.

**Comment by leculver** [comment]
Ah nevermind, I'm just dumb.  =)

I set my PATH incorrectly, used a windows syntax instead of linux.

**Comment by NextTurn** [comment]
But why did you merge this before verifying it?

**Comment by leculver** [comment]
It was fairly scoped to Linux and didn't seem like it would hurt anything, so I merged it to get the PR out of the way in case my larger changes coming down the pipe would conflict.  Also you seem to know what you are doing so I didn't stress too much about it.  =)

**Pull request merged**
