### PR TITLE
Enable incremental build on Linux

### PR DESCRIPTION
**Pull request by NextTurn**

### CODE REVIEW

**Comment by leculver** [comment]
Would you mind rebasing this on testing/2.0?    Right now the master branch is paused as I get the 2.0 refactoring done, so if this is open against master it'll sit here for a while until I'm reading to merge testing/2.0.  (Same for any other open PRs.)

FYI now that the giant refactoring is done future deltas will be much smaller so I'll be merging PRs quicker.

**Comment by NextTurn** [comment]
This PR is based on #335 which was merged into master, so it's easier to keep it target master to avoid possible future conflicts (when merging testing/2.0).

**Comment by leculver** [comment]
Ah ok, sorry for my confusion.  Re-target master then and I'll merge this one.

**Comment by leculver** [comment]
Had to roll this one back due to build issues:

```
  
  Time Elapsed 00:00:01.08
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(153,5): error MSB3680: The source file "Arrays/coredump" does not exist.
##[error]src/TestTargets/TestTargets.proj(153,5): error MSB3680: The source file "Arrays/coredump" does not exist.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Arrays"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/ClrObjects"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/FinalizationQueue"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCHandles"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/GCRoot2"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/NestedException"" exited with code 131.
  A fatal error occurred. The required library libhostfxr.so could not be found.
  If this is a self-contained application, that library should exist in [/__w/1/s/src/TestTargets/bin/x64/].
  If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
##[error]src/TestTargets/TestTargets.proj(152,5): error MSB3073: The command ""/__w/1/s/src/TestTargets/bin/x64/Types"" exited with code 131.
/__w/1/s/src/TestTargets/TestTargets.proj(153,5): error MSB3680: The source file "Arrays/coredump" does not exist.
##[error]src/TestTargets/TestTargets.proj(153,5): error MSB3680: The source file "Arrays/coredump" does not exist.
  Running tests: /__w/1/s/artifacts/bin/Microsoft.Diagnostics.Runtime.UnitTests/Debug/netcoreapp3.0/Microsoft.Diagnostics.Runtime.UnitTests.dll [netcoreapp3.0|x64]
  Tests succeeded: /__w/1/s/artifacts/bin/Microsoft.Diagnostics.Runtime.UnitTests/Debug/netcoreapp3.0/Microsoft.Diagnostics.Runtime.UnitTests.dll [netcoreapp3.0|x64]
  Successfully created package '/__w/1/s/artifacts/packages/Debug/Shipping/Microsoft.Diagnostics.Runtime.1.1.0-ci.nupkg'.```

I'm still working on getting PR builds turned on for the repo.

**Comment by NextTurn** [comment]
Using `dotnet` CLI to run the executables may resolve the failures. Shall I open a new one?

**Comment by leculver** [comment]
Sure open a new one.  The overall change itself is fine, it just reacted badly running build.sh.  I'll test the next PR before merging.  =)

**Pull request merged**
