### PR TITLE
Add IThreadReader

### PR DESCRIPTION
**Pull request by leculver**
- Added an optional interface for IDataReaders which preserves some ClrMD 1.1 functionality.
- WindowsLiveDataTarget doesn't currently implement this.

### CODE REVIEW

**Comment by mikem8361** [comment]
Is this ready to merge?

**Comment by mikem8361** [comment]
I didn’t catch this until now but are you sure you want IThreadReader in the Microsoft.Diagnostics.Runtime.DataReaders.Implementation namespace? The rest of data readers are in just Microsoft.Diagnostics.Runtime.

**Comment by mikem8361** [comment]
It also looks like the EnumerateOSThreads() on the Windows minidump reader no longer puts the "Main" thread first.  

This is different kind of breaking behavior for dotnet-dump.

**Comment by leculver** [comment]
@mikem8361 Do you need signed packages to test this?  I can give them to you offline if so.

> are you sure you want IThreadReader in the Microsoft.Diagnostics.Runtime.DataReaders.Implementation namespace?

I'm about 75% sure I want it in the Implementation namespace.  =)

The underlying idea here is that this is a very, very special case that really only SOS/dotnet-diagnostics is using.  Having "hidden" interfaces is wacky enough, and I want to make sure people are truly opting into them.  I also considered changing it from .Implementation to M.D.R.Optional as a way to say "hey these might not be implemented."

> It also looks like the EnumerateOSThreads() on the Windows minidump reader no longer puts the "Main" thread first.

I'll see how fixable this is.  I need to chase down some issues that came in over the weekend this morning (and mondays I have a lot of meetings) but I'll do this today between meetings.

**Comment by mikem8361** [comment]
The namespace is ok with me. I just wanted to make sure it wasn't a typo. 

I understand about how busy you.  Whenever you get time to look at the thread enumeration order.

**Comment by leculver** [comment]
> I understand about how busy you. Whenever you get time to look at the thread enumeration order.

This is still my top priority, I want to get this wrapped up while it's fresh.

**Pull request merged**
