### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by leculver**
- Updated nuget dependencies.
- Fixed a few warnings.

### CODE REVIEW

**Comment by arvindshmicrosoft** [comment]
Thank you @leculver - would you be publishing another Nuget for RC or will this change make it directly to RTM?

**Comment by leculver** [comment]
I plan to RTM on Friday if all goes to plan so I wasn't planning another RC build.  Note I also need to make one more breaking change that I intended earlier but forgot:  https://github.com/microsoft/clrmd/issues/717.

**Comment by leculver** [comment]
@arvindshmicrosoft Though if you need a new RC build I can upload one now.  It only takes a few minutes.  Just let me know.

**Comment by leculver** [comment]
@arvindshmicrosoft Ah sorry for the quick reversal, but yes I will push a new RC tonight.  I forgot I need to publish an RC to do a final update to samples.

**Comment by NextTurn** [comment]
> * Updated nuget dependencies.

[Dependabot](https://help.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically) can do the job for you.

**Pull request merged**
