### PR TITLE
Convert to jobs.yml

### PR DESCRIPTION
**Pull request by chcosta**

### CODE REVIEW

**Comment by chcosta** [comment]
@leculver , does this repo intentionally not have any CI gates for PR's?

**Comment by chcosta** [comment]
@leculver, this is *mostly* working.  A couple of open issues...

- Where are your builds?  I don't see any PR builds happening, and I saw that you had code in dnceng so I pushed changes there for validation, but it doesn't look like your official build definition in dnceng is actually used.
- I validated the changes I'm making in dnceng - https://dnceng.visualstudio.com/internal/_build/results?buildId=242415
- The build is complaining about some issue with the license.  You probably make a change similar to https://github.com/dotnet/iot/pull/356/files, but since I don't know what license you want to use, I don't feel safe making that change.

I'm OOF for a few days, please feel free to take these changes to unblock yourself.

**Comment by leculver** [comment]
@chcosta The builds I had before lived here:  https://dnceng.visualstudio.com/internal/_build?definitionId=232

I see your pulls there, but the builds are failing...  I assume that's the license issue.

We are MIT licensed.  I will look at making those changes tomorrow.

**Comment by mikem8361** [comment]
I took your PR, fixed the license issue and merged it in. You can close this PR.

**Pull request closed without merging**
